import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='de'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='p-4'>
          <nav className='flex gap-4'>
            <Link href='/'>Startseite</Link>
            <Link href='/profil'>Über mich</Link>
            <Link href='/leistungen'>Leistungen</Link>
            <Link href='/projekte'>Projekte</Link>
            <Link href='/kontakt'>Kontakt</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
